### ISSUE TITLE
App cloned from github doesn't start

### ISSUE THREAD

**Issue by grzanka** [intdata-bsc/idact-gui#35]
![image](https://user-images.githubusercontent.com/7374733/68495783-356a8000-0251-11ea-8e74-cb4b8eb6c0fa.png)

**Comment by PiekarzKarolina** [comment]
Please use the `python -m gui.main` command inside the `idact-gui` folder. I'll shortly add readme for that.

**Comment by PiekarzKarolina** [comment]
I've added the readme, please use the commands listed there.
